version: '3.8'

services:
  quiz-app:
    build: .
    container_name: namorada-quiz
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DATABASE_PATH=/app/data/quiz.db
      - ADMIN_PASSWORD=admin123  # Mude isso!
      - JWT_SECRET=seu-super-secret-jwt-key-aqui  # Mude isso!
    volumes:
      - quiz_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  quiz_data:
    driver: local

networks:
  default:
    name: quiz-network
