version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/quiz_namorada.db
      - JWT_SECRET=${JWT_SECRET:-change-this-secret-in-production}
      - TZ=America/Sao_Paulo
      - PORT=8080
    volumes:
      - app_data:/data
    restart: unless-stopped

volumes:
  app_data:
