version: '3.8'

services:
  # Aplicação principal
  valentine-quiz:
    build: .
    expose:
      - "8080"  # Expor só internamente, não para o host
    environment:
      - GIN_MODE=release
      - PORT=8080
      - DB_PATH=/data/quiz.db
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - VISITOR_USERNAME=${VISITOR_USERNAME:-momo}
      - VISITOR_PASSWORD=${VISITOR_PASSWORD:-momo3006}
      - JWT_SECRET=${JWT_SECRET:-change_this_in_production}
    volumes:
      - quiz_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - quiz_network
  # Proxy reverso HTTP simples
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"     # Só HTTP por enquanto
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites/:/etc/nginx/conf.d/:ro
    depends_on:
      - valentine-quiz
    restart: unless-stopped
    networks:
      - quiz_network

volumes:
  quiz_data:
    driver: local

networks:
  quiz_network:
    driver: bridge
